config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: %i[show]
  get 'search', to: 'recipes#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :instructions, dependent: :destroy

  enum status: { cho_zubora: 0, zubora: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:ingredient1].nil?
      @recipes = Recipe.order("RAND()").limit(10)
    else
      @recipes = Recipe.joins(:ingredients).where(ingredients: {name: params[:ingredient1]})
                     .or(Recipe.joins(:ingredients).where(ingredients: {name: params[:ingredient2]}))
                     .or(Recipe.joins(:ingredients).where(ingredients: {name: params[:ingredient3]}))
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def search
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zubora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<section id="top">
  <div class="top-title-img">
    <div class="top-title-contents">
      <h1>3分で作れる<br>ズボラ飯レシピ</h1>
      <div>
        <%= link_to  'ズボラ検索する', search_path ,:class => "search-button"%>
        <%= image_tag("search.svg", :alt=>"検索") %>
      </div>
    </div>
  </div>
  <div class="contents">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe) do %>
        <div class="tile">
          <% if recipe.status == "cho_zubora" %>
            <%= image_tag("cho.svg", :alt => "超ズボラ", :class=>"cho-icon") %>
          <% end %>
          <%= image_tag("#{recipe.image}", :alt => "肉じゃがの画像") %>
          <p><%= recipe.name %></p>
        </div>
      <% end %>
    <% end %>
    <div class="do-not-select">
      <p>ズボラ過ぎて</p>
      <p>選べない</p>
    </div>
  </div>
</section>

app/views/recipes/search.html.erb
<main>
  <h1>レシピを決めよう</h1>
  <section>
    <h2>今ある食材</h2>
    <button onclick="modalOpen()">
      <div id="selectedFood"></div>
    </button>
  </section>
  <section>
    <h2>ジャンル</h2>
    <div class="genre">
      <button id="zubora" onclick="onZubora()">ズボラ飯</button>
      <div>
        <button id="superZubora" onclick="onSuperZubora()">超ズボラ飯</button>
        <div>食材３つ以下</div>
      </div>
    </div>
  </section>
  <button class="main_button" onclick="search()">検索する</button>
</main>

<div id="modal">
  <section>
    <h2>食材を選ぶ</h2>
    <div class="foodSelector">
      <button onclick="selectFood(this)" id="トマト"><div class="badge"></div><img src="/assets/tomato.png" alt="ピーマン"></button>
      <button onclick="selectFood(this)" id="ピーマン"><div class="badge"></div><img src="/assets/greenpepper.png" alt="ピーマン"></button>
      <button onclick="selectFood(this)" id="牛肉"><div class="badge"></div><img src="/assets/beef.png" alt="牛肉"></button>
    </div>
    <div class="foodSelector">
      <button onclick="selectFood(this)" id="たまねぎ"><div class="badge"></div><img src="/assets/onion.png" alt="たまねぎ"></button>
      <button onclick="selectFood(this)" id="にんじん"><div class="badge"></div><img src="/assets/carrots.png" alt="にんじん"></button>
      <button onclick="selectFood(this)" id="たまご"><div class="badge"></div><img src="/assets/egg.png" alt="たまご"></button>
    </div>
  </section>
  <button class="main_button" onclick="decideFood()">OK</button>
</div>

app/views/recipes/show.html.erb
<article id="recipes-index">
  <%= image_tag(@recipe.image, alt: "recipe_img")%>
  <h1><%= @recipe.name %></h1>
  <section class="source">
    <h2 class="source-title">食材（1人分）</h2>
    <% @recipe.ingredients.each do |ingredient| %>
      <ul>
        <li>
          <span class="name"><%= ingredient.name %></span>
          <span class="amount"><%= ingredient.quantity %></span>
        </li>
      </ul>
    <% end %>
  </section>
  <section class="recipes">
    <h2 class="recipes-title">レシピ</h2>
    <% @recipe.instructions.each do |instruction| %>
      <ul>
        <li><%= "#{instruction.sort_order}. #{instruction.body}" %></li>
      </ul>
    <% end %>
  </section>
</article>

app/views/shared/_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag("logo.svg", :alt => "Zubora logo", :class => "logo") %>
  <% end %>
</header>